"""
generate_sample_data.py

Generates a SMALL, SYNTHETIC-BUT-STRUCTURALLY-REALISTIC sample dataset for
local development, because live INCOIS/Copernicus/Ifremer sources are not
reachable from this environment (auth/network restricted).

This script is a STAND-IN for a real download step. It writes files with the
exact variable names, dimensions, and conventions a real Copernicus
GLOBAL_MULTIYEAR_PHY extract and a real Argo GDAC profile set would have, so
scripts/preprocess.py exercises a realistic ingestion path. Swapping in real
files later requires no changes to preprocess.py's normalization logic --
only a new "source adapter" if the real files use different variable names.

Domain: Bay of Bengal box (matches INCOIS's primary operational area)
  lat: 8..18 N, lon: 82..92 E
Depths: 0..500m, 8 levels (positive down, meters) -- matches typical
  upper-ocean Argo/Copernicus levels
Time: 8 daily steps
Variables: thetao (temperature, degC), so (salinity, PSU) -- Copernicus names

Output:
  data/raw/sample_ocean_model.nc   (model field)
  data/raw/sample_argo_profiles.nc (18 synthetic Argo-style profiles)
"""
import numpy as np
import xarray as xr
import pandas as pd

OUT_DIR = "data/raw"
RNG = np.random.default_rng(42)  # deterministic -- reproducible sample

# ---------- Model grid ----------
N_LAT, N_LON, N_DEPTH, N_TIME = 60, 60, 8, 8

lats = np.linspace(8.0, 18.0, N_LAT)
lons = np.linspace(82.0, 92.0, N_LON)
depths = np.array([0, 10, 25, 50, 100, 150, 250, 500], dtype=float)  # meters, positive down
times = pd.date_range("2026-09-01", periods=N_TIME, freq="D")

LAT2D, LON2D = np.meshgrid(lats, lons, indexing="ij")

# A simple synthetic "land mask": treat a corner as land to force the
# pipeline to handle NaN / missing-value correctly (real data always has this).
land_mask = (LAT2D > 16.5) & (LON2D < 84.0)

def synth_temperature(depth_m, lat, lon, day_idx):
    """Warm tropical surface, realistic thermocline decay with depth,
    mild spatial gradient (cooler north/east), tiny day-to-day drift."""
    surface_temp = 29.5 - 0.15 * (lat - 8.0) - 0.05 * (lon - 82.0)
    thermocline_drop = 8.5 * (1 - np.exp(-depth_m / 90.0))
    seasonal_noise = 0.15 * np.sin(day_idx / 3.0)
    return surface_temp - thermocline_drop + seasonal_noise

def synth_salinity(depth_m, lat, lon, day_idx):
    """Lower surface salinity near coast/river influence (west/north),
    increasing slightly with depth (halocline), small day-to-day drift."""
    surface_sal = 33.2 + 0.08 * (lon - 82.0) - 0.03 * (lat - 8.0)
    halocline_rise = 1.2 * (1 - np.exp(-depth_m / 120.0))
    seasonal_noise = 0.03 * np.cos(day_idx / 4.0)
    return surface_sal + halocline_rise + seasonal_noise

thetao = np.empty((N_TIME, N_DEPTH, N_LAT, N_LON), dtype=np.float32)
so = np.empty((N_TIME, N_DEPTH, N_LAT, N_LON), dtype=np.float32)

for ti in range(N_TIME):
    for di, d in enumerate(depths):
        t_field = synth_temperature(d, LAT2D, LON2D, ti) + RNG.normal(0, 0.05, LAT2D.shape)
        s_field = synth_salinity(d, LAT2D, LON2D, ti) + RNG.normal(0, 0.02, LAT2D.shape)
        t_field[land_mask] = np.nan
        s_field[land_mask] = np.nan
        thetao[ti, di] = t_field
        so[ti, di] = s_field

ds = xr.Dataset(
    data_vars=dict(
        thetao=(["time", "depth", "latitude", "longitude"], thetao, {
            "units": "degrees_C", "long_name": "Sea water potential temperature",
            "standard_name": "sea_water_potential_temperature",
        }),
        so=(["time", "depth", "latitude", "longitude"], so, {
            "units": "1e-3", "long_name": "Sea water salinity",
            "standard_name": "sea_water_salinity",
        }),
    ),
    coords=dict(
        time=times,
        depth=("depth", depths, {"units": "m", "positive": "down"}),
        latitude=("latitude", lats, {"units": "degrees_north"}),
        longitude=("longitude", lons, {"units": "degrees_east"}),
    ),
    attrs=dict(
        title="Representative synthetic dataset -- architecture validated for real ocean "
              "NetCDF/Argo ingestion. NOT live INCOIS/Copernicus data.",
        source="Generated by scripts/generate_sample_data.py -- NOT live INCOIS/Copernicus data",
        conventions="CF-1.8 (structurally matches Copernicus GLOBAL_MULTIYEAR_PHY_001_030)",
        note="Structurally realistic synthetic data. Ingestion pipeline (scripts/preprocess.py) "
             "is designed to accept real NetCDF with the same variable names (thetao, so) "
             "with no changes to normalization logic.",
    ),
)

import os
os.makedirs(OUT_DIR, exist_ok=True)
ds.to_netcdf(f"{OUT_DIR}/sample_ocean_model.nc")
print(f"Wrote {OUT_DIR}/sample_ocean_model.nc  dims={dict(ds.sizes)}")

# ---------- Synthetic Argo-style profiles ----------
# IMPORTANT: profiles are derived FROM the model field (via the same
# analytic functions used to build thetao/so, i.e. the "true" underlying
# field) plus a deterministic, physically-plausible observation-model
# discrepancy (small constant bias + small per-level noise). This means
# the model-vs-observation comparison in the API is NOT comparing a float
# against itself -- it reproduces a realistic, non-zero, reproducible
# bias/MAE/RMSE, the same way a real Argo float would differ slightly from
# a real numerical ocean model at its location.
N_FLOATS = 18
float_lats = RNG.uniform(8.5, 17.5, N_FLOATS)
float_lons = RNG.uniform(82.5, 91.5, N_FLOATS)
# keep floats off the synthetic "land" corner
for i in range(N_FLOATS):
    while (float_lats[i] > 16.5) and (float_lons[i] < 84.0):
        float_lats[i] = RNG.uniform(8.5, 17.5)
        float_lons[i] = RNG.uniform(82.5, 91.5)

profile_depths = np.array([0, 10, 25, 50, 100, 150, 250, 500, 750, 1000], dtype=float)

# Deterministic per-variable "instrument discrepancy" -- fixed bias + fixed
# depth-dependent noise pattern (seeded), representative of real sensor
# offset + sampling error, so comparisons are meaningful and reproducible.
TEMP_OBS_BIAS = -0.35   # floats read slightly cooler than the model, on average
SAL_OBS_BIAS = 0.12     # floats read slightly saltier than the model, on average

all_temp = np.empty((N_FLOATS, len(profile_depths)), dtype=np.float32)
all_psal = np.empty((N_FLOATS, len(profile_depths)), dtype=np.float32)
all_time = []
platform_ids = []

for i in range(N_FLOATS):
    day_idx = RNG.integers(0, N_TIME)
    all_time.append(times[day_idx])
    platform_ids.append(f"29{6000 + i:04d}")  # realistic-looking WMO-style Argo ID
    for di, d in enumerate(profile_depths):
        # "true" field value at this exact location/depth/time, from the
        # same generating function used for the model NetCDF
        true_t = synth_temperature(d, float_lats[i], float_lons[i], day_idx)
        true_s = synth_salinity(d, float_lats[i], float_lons[i], day_idx)
        # deterministic per-level noise (seeded RNG, reproducible across runs)
        t_noise = RNG.normal(0, 0.15)
        s_noise = RNG.normal(0, 0.05)
        all_temp[i, di] = true_t + TEMP_OBS_BIAS + t_noise
        all_psal[i, di] = true_s + SAL_OBS_BIAS + s_noise

argo_ds = xr.Dataset(
    data_vars=dict(
        TEMP=(["N_PROF", "N_LEVELS"], all_temp, {"units": "degree_Celsius", "long_name": "Sea temperature"}),
        PSAL=(["N_PROF", "N_LEVELS"], all_psal, {"units": "psu", "long_name": "Practical salinity"}),
        PRES=(["N_LEVELS"], profile_depths, {"units": "decibar", "long_name": "Sea water pressure, equals depth approx"}),
        LATITUDE=(["N_PROF"], float_lats, {"units": "degrees_north"}),
        LONGITUDE=(["N_PROF"], float_lons, {"units": "degrees_east"}),
        JULD=(["N_PROF"], np.array(all_time, dtype="datetime64[ns]")),
        PLATFORM_NUMBER=(["N_PROF"], np.array(platform_ids)),
    ),
    attrs=dict(
        title="Representative synthetic dataset -- architecture validated for real ocean "
              "NetCDF/Argo ingestion. NOT live Ifremer GDAC data.",
        source="Generated by scripts/generate_sample_data.py -- NOT live Ifremer GDAC data",
        conventions="Argo NetCDF variable naming convention (TEMP/PSAL/PRES/LATITUDE/LONGITUDE/JULD/PLATFORM_NUMBER)",
        note="Values derived from the same analytic field as sample_ocean_model.nc plus a "
             "deterministic, seeded observation-model discrepancy (bias + noise), so "
             "model-vs-observation comparisons are meaningful and reproducible. Standing in "
             "for real Argo floats until Ifremer GDAC access is available from the "
             "deployment environment.",
    ),
)
argo_ds.to_netcdf(f"{OUT_DIR}/sample_argo_profiles.nc")
print(f"Wrote {OUT_DIR}/sample_argo_profiles.nc  N_PROF={N_FLOATS}, N_LEVELS={len(profile_depths)}")
